---
title: "Lab 14 - Regression Trees"
author: Tejas Dhomne
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: simplex
    number_sections: false
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

## 0 load the packages 
```{r}
library(rpart)
library(rpart.plot)

```

## 1 create a data frame
```{r}
# load the data 
df <- read.csv("BostonHousing.csv")
# remove the variable CAT..MEDV
housing.df = subset(df, select = -c(CAT..MEDV) )
# first six rows 
head(housing.df)
# column names
names(housing.df)
```

## 2 data partition
```{r}
# set the seed 
set.seed(1) 
# row numbers of the training set
train.index <- sample(c(1:dim(housing.df)[1]), dim(housing.df)[1]*0.6)  
head(train.index)

# training set
train.df <- housing.df[train.index,]
head(train.df) 

# test set 
test.df <- housing.df[-train.index,]
head(test.df)
```

## 3 fit a shallow regression tree
```{r}
# regression tree with cp = 0.5
rt.shallow <- rpart(MEDV ~ ., cp=0.5, data=train.df, method = "anova")
# plot the tree
prp(rt.shallow, type = 1, extra = 1)
# predicted prices for records in the test set 
rt.shallow.pred <- predict(rt.shallow, test.df,type="vector")
# first six values 
head(rt.shallow.pred)
# MSE in the test set 
mean((test.df$MEDV-rt.shallow.pred)^2)
```

## 4 fit a deeper regression tree  
```{r}
# regression tree with cp = 0.01
rt.deep <- rpart(MEDV ~ ., cp=0.01, data=train.df, method = "anova")
# plot the tree
prp(rt.deep, type = 1, extra = 1)
# predicted prices for records in the test set 
rt.deep.pred <- predict(rt.deep, test.df,type="vector")
# first six values 
head(rt.deep.pred)
# MSE in the test set 
mean((test.df$MEDV-rt.shallow.pred)^2)
```

## 5 prune the regression tree 
```{r}
# set the seed 
set.seed(1)
# fit a regression tree with cp = 0.0001 and xval = 5
cv.rt <- rpart(MEDV ~ ., data = train.df, method = "anova", cp=0.001, xval=5)
# display the cp table
cv.rt$cptable
# xerror values 
cv.rt$cptable[,"xerror"]
# index of the row with the minimum xerror
which.min(cv.rt$cptable[,"xerror"]) 
# CP value of the row with the minimum xerror 
cv.rt$cptable[which.min(cv.rt$cptable[,"xerror"]),"CP"]
```

## 6 identify the best-pruned regression tree   
```{r}
# prune the tree
rt.pruned <- prune(cv.rt, cv.rt$cptable[which.min(cv.rt$cptable[,"xerror"]),"CP"])
# plot the tree
prp(rt.pruned, type = 1, extra = 1)
# predicted prices for records in the test set 
rt.pruned.pred <- predict(rt.pruned, test.df, type="vector")
# first six values 
head(rt.pruned.pred)
# MSE in the test set 
mean((test.df$MEDV-rt.pruned.pred)^2)
```

