---
title: "Lab 09 - Discriminant Analysis"
author: Tejas Dhomne
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: simplex
    number_sections: false
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

## 0 load the packages 
```{r}
library(DiscriMiner)
library(caret)
library(gains)

```

## 1 create a data frame
```{r}
# load the data
df <- read.csv("SystemAdministrators.csv")
# first six rows
head(df)
# column names 
colnames(df)
```

## 2 data partition 
```{r}
# set seed for reproducing the partition 
set.seed(1)
# row numbers of the training set 
train.index <- sample(c(1:dim(df)[1]), dim(df)[1]*0.6) 
# row numbers of the test set 
test.index <- setdiff(row.names(df), train.index)
```

## 3 perform a discriminant analysis using the training set
```{r}
# run a discriminant analysis using the training set
da.reg <- linDA(df[train.index,1:2], df[train.index,3])
# classification function 
da.reg$functions
# poor administrator score (class=No)
da.reg$scores[,1]
# good administrator score (class=Yes)
da.reg$scores[,0]
# predicted classes 
da.reg$classification
```

## 4 making predictions for records in the test set  
```{r}
# classify observations in the test set 
head(df[test.index,1:2])
pred <- classify(da.reg, newdata = df[test.index,1:2])
# classification scores 
head(pred$scores)
# predicted probabilities of being a good administrator 
prob.accept <- exp(pred$scores[,2])/(exp(pred$scores[,1])+exp(pred$scores[,2]))
head(prob.accept)
# predicted classes 
head(pred$pred_class)
```

## 5 confusion matrix 
```{r}
confusionMatrix(pred$pred_class, as.factor(df[test.index,3]), positive = "Yes")

```

## 6 creating a gain table 
```{r}
# gain table 
library(gains)
gain <- gains( ifelse(df[test.index,3]=="Yes",1,0) , prob.accept, groups = 5)
# cumulative percentage of good administrators  
gain$cume.pct.of.tota
# cumulative number of administrators
gain$cume.obs
```

## 7 plot a lift chart
```{r}
# plot the cumulative number of good administrators against the cumulative number of administrators
plot(c(0,gain$cume.pct.of.total*sum(df[test.index,3]=="Yes"))~c(0,gain$cume.obs), 
     xlab="cumulative number of administrators", ylab="cumulative number of good administrators", type="l")
# add a baseline curve 
lines(c(0,sum(df[test.index,3]=="Yes")) ~ c(0,dim(df[test.index,])[1]))
```